apiVersion: v1
kind: Service
metadata:
  name: attendance-backend-service
spec:
  selector:
    app: attendance-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
